### PR TITLE
Added optional `depends` and `optdepends` keys

### PR DESCRIPTION
**Pull request by margual56**
[asciicast](https://asciinema.org/a/7cQh7i97Cu3uPdbGfebjPPxnS)

## Why?
`depends` and `optdepends` are often needed when creating an AUR package. Not "cargo" dependencies, but other programs such as `mpv` to play videos.

## How?
This pull request adds two optional manifest keys: `depends` and `optdepends`, which are arrays of strings containing the name of the program's dependencies.

Since they are optional, this version will remain backwards-compatible. Empty arrays will be generated if not present in the Cargo.toml

## Possible improvements
- When compiling, cargo warns about "unused manifest keys" (because `depends` and `optdepends` are not valid cargo package keys).

### CODE REVIEW

**Comment by margual56** [comment]
> Is there not a way to tell Cargo "Hey this is a custom key that I'm using elsewhere, don't worry about it"?

After some digging, I found that there exists the [`[package.metadata]` table](https://doc.rust-lang.org/cargo/reference/manifest.html#the-metadata-table), and indeed with the keys inside that table, no warning is displayed.

I will try to shuffle a couple things and see if I can get stuff parsed from the `package.metadata`, that should solve the issue :)

**Comment by margual56** [comment]
That works! I tried to tidy it up somewhat, I hope the formatting and comments are okey.

Open to suggestions 😃

**Comment by fosskers** [comment]
Fantastic, I'll take a look.

**Comment by fosskers** [comment]
Github will show the merge status incorrectly, but this was indeed merged! Check the `master` branch. Once you've signed off, I'll close this PR.

**Comment by fosskers** [comment]
I've released `1.5.0` with this included.

**Comment by margual56** [comment]
Nice! Thank you 😊

**Pull request closed without merging**
